image: golang:1.23

before_script:
  - echo 'start :before_script'
  - cat /etc/os-release
  - echo 'end :before_script'

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test

unit-test:
  stage: test
  script:
    - go mod tidy
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile unittest.xml --format testname
  only:
    - main
  artifacts:
    when: always
    reports:
      junit: unittest.xml

coverage-test:
  stage: test
  script:
    - go mod tidy
    - go install
    - go test ./... -coverprofile=coverage.txt -covermode count
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
  coverage: '/coverage: \d+.\d+% of statements/'
  only:
    - main
  artifacts:
    name: $CI_JOB_NAME/coverage.txt
    paths:
      - coverage.xml
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

semgrep-sast:
  variables:
    SAST_ANALYZER_IMAGE_TAG: "3.7"
    GITLAB_ADVANCED_SAST_ENABLED: 'true'
  rules:
    - if: $SAST_DISABLED == 'true' || $SAST_DISABLED == '1'
      when: never
    - if: $SAST_EXCLUDED_ANALYZERS =~ /phpcs-security-audit/
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      when: always
    - if: $CI_COMMIT_BRANCH
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Add the job to merge request pipelines if there's an open merge request.
      exists:
        - '**/*.go'
    - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
      when: never