FROM golang:1.22-alpine3.19 as builder

ARG GO_BUILD_COMMAND="go build -tags static_all"

# Install some build deps + ssh tools for the setup below.
RUN apk update && apk --no-cache add  build-base  git bash  coreutils openssh  openssl


# this command if you get source from bitbucket repos
# Create the directory where the application will reside
RUN mkdir -p /go/src/gitlab.com/sirioid/go-boilerplate

WORKDIR /go/src/gitlab.com/sirioid/go-boilerplate

# application builder step
RUN go mod tidy && go mod download && go mod vendor
RUN eval $GO_BUILD_COMMAND

# STEP 2 build a small image
# Set up the final (deployable/runtime) image.
FROM alpine:3.19.0


# setup package dependencies
RUN apk --no-cache update && apk --no-cache  add  ca-certificates bash jq curl gettext

ENV BUILDDIR=/go/src/gitlab.com/sirioid/go-boilerplate
ENV PROJECT_DIR=/opt/go-boilerplate

# Setting timezone
ENV TZ=Asia/Jakarta
RUN apk add -U tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set ENV variable for Datadog Build Version
ARG BUILD_VERSION
ENV DD_VERSION=$BUILD_VERSION

#create project directory
RUN mkdir -p $PROJECT_DIR/config
RUN mkdir -p $PROJECT_DIR/database/migration

WORKDIR $PROJECT_DIR

COPY --from=builder $BUILDDIR/go-boilerplate go-boilerplate
COPY --from=builder $BUILDDIR/config/app.yaml.dist $PROJECT_DIR/config/app.yaml.dist
COPY --from=builder $BUILDDIR/database/migration $PROJECT_DIR/database/migration
# COPY --from=builder $BUILDDIR/config/msg.yaml $PROJECT_DIR/config/msg.yaml

CMD ["sh","-c", "/opt/go-boilerplate/go-boilerplate http"]
